FROM node:10

# Create app directory
WORKDIR /usr/src/WaterMe_MQTT_Client

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

CMD [ "npm", "run", "start_mqtt_client" ]